name: Build ComfyUI Anima

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true

          tags: |
            12el3rlll/comfyui-anima:v8
            12el3rlll/comfyui-anima:latest

          cache-from: |
            type=registry,ref=12el3rlll/comfyui-anima:buildcache
            type=gha

          cache-to: |
            type=registry,ref=12el3rlll/comfyui-anima:buildcache,mode=max
            type=gha,mode=max
